Task 1 4 2
Alowator/OOP pull request #4
Opened 2021-11-16 16:11 UTC by Alowator

Недостаточно тестов, нет оболочки для консольного управления. Скоро будут...

2021-11-17 11:50 UTC, Leidenn2509 requested changes
Нужно добавить работу с консолью и json
И я не уверен насчёт таймера. Точно ли он нужен?

2021-11-17 11:50 UTC, Leidenn2509 commented on Task_1_4_2/src/main/java/ru/nsu/alowator/notebook/Note.java
> +public class Note {
У заметок есть название

2021-11-29 14:15 UTC, Alowator commented
Для создания .jar необходимо запустить task: build.gradle -> jar

2021-11-30 07:50 UTC, Leidenn2509 approved these changes

2021-11-30 07:50 UTC, merged