Create Tree(), Node()
Alowator/OOP pull request #5
Opened 2021-12-15 21:31 UTC by Alowator

Не успел сделать тесты. Возможно все равно что-то придется менять) Еще не хватает возможности добавлять деревья и отпочковывать их. Но в моей архитектуре это не так сложно добавить.

**Идея** у меня такая - оперировать можно только классом `Tree`. Класс `Node` это для внутренний реализации дерева, чтобы код получше был. Соответственно пользователь добавляет туда и получает оттуда объекты. Тогда бы класс `Node` запихать внутрь класса `Tree` и сделать его `private`, но как-то не хочется, там и так 2 итератора уже внутри.... А способа сделать Node недоступным из вне другого пока не нашел. 

`add()` - если дерево пустое, элемент становится корнем, иначе становится сыном корня.
`remove()` - удаляет именно элемент, не поддерево. Его детей усыновляет прародитель, если элемент корень, то корнем становится один из детей и усыновляет остальных. _Это, видимо, стоит задокументировать в коде_

2021-12-17 12:47 UTC, Leidenn2509 requested changes
- javadoc
- tests

2021-12-17 12:47 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/alowator/Tree/Node.java
> +    List<Node> children;
private

2021-12-17 12:47 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/alowator/Tree/Tree.java
> +    private final Map<Object, Node> map;
По названию переменной не совсем понятно, что она хранит

2021-12-17 12:47 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/alowator/Tree/Tree.java
> +public class Tree<T> implements Collection<Object> {
Надо бы использовать T

2021-12-23 18:55 UTC, Alowator commented
Все замечания исправил.

2021-12-24 12:01 UTC, Leidenn2509 requested changes

2021-12-24 12:01 UTC, alradish commented on Task_1_2_2/src/main/java/ru/nsu/alowator/Tree/Node.java
> +public class Node {
Используйте T

2021-12-24 12:01 UTC, alradish commented on Task_1_2_2/src/main/java/ru/nsu/alowator/Tree/Tree.java
> +    public boolean add(Object value) {
```java
add(T value)
```
В коллекцию всё же можно добавлять только T

2021-12-24 18:41 UTC, Leidenn2509 commented
А. Забыл написать про get. У вас нет возможность получать данные. Нужно, чтобы можно было получать поддеревья

2021-12-24 19:59 UTC, Alowator commented
Внес необходимые изменения. 

Вообще да, понимаю, что правильнее использовать сразу было везде (где необходимо) T, однако интерфейс меня запутал, тк в остальных функциях (типо `contains()`) в контракте именно `Object`. Вот я по инерции и запихал `Object` везде, где не надо. 

По-началу просто не осознал, почему используем `add(T value)`, но `remove(Object obj)`. Несколько раз поправив код, осознание, видимо, пришло. Дело в том, что добавляем точно `T`, а вот удаляя используем, допустим, `equals(Object obj)`, где поведение может быть иным, т.е. действительно можно передать туда другой тип (Например - другого наследника родителя `T`), и ожидать верного поведения при вызове `equals`.

2021-12-24 20:47 UTC, Leidenn2509 approved these changes

2021-12-24 20:47 UTC, merged