Task_2_1_1
Alowator/OOP pull request #6
Opened 2022-02-18 21:17 UTC by Alowator

### Архитектура такова:
* `App` - запускает замеры
* `Runner` - замеряет время работы всех `Finder`-ов, которые ему передают
* `Calculus` - static модуль с вычислениями (`isPrime`)
* `impl/NotPrimeFinder` -  последовательная реализация, он же базовый `Finder`, все остальные реализации должны унаследоваться от этого класса и переопределять `run()` (хотелось бы сделать `implements Runnable`, однако функция должна возвращать `boolean`, поэтому делаем свой `run()`)

### Чего не хватает и что появится в ближайшее время:
- `ThreadNotPrimeFinder` - реализация через Thread
- Unit тесты для `Calculus` и `*NotPrimeFinder`
- `Runner` нуждается в доработке (прогревать перед `f.run()`, считать время как среднее)
- Вывод полученных данных в виде графика (нужен какой-нибудь интерфейс в `Runner`, или еще где-нибудь, с которого удобно будет что-нибудь выводить и рисовать)

### Если я где-то не прав или что-то упустил, прошу поправить

2022-02-21 10:03 UTC, Leidenn2509 requested changes

2022-02-21 10:03 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/alowator/impl/NotPrimeFinder.java
> +    public boolean run() {
Возможно вам подойтёт `Callable<V>`

2022-02-21 10:03 UTC, Leidenn2509 commented on Task_2_1_1/src/main/java/ru/nsu/alowator/App.java
> +    private static void fillArrayWithPrimePositiveNumbers(Integer[] array) {
Для наглядности советую использовать таблицы простых числе и взять от туда что-то большое (чтобы нагрузка на `isPrime` была больше). Предлагаю кучу 1048571(простое) и одно 1048561(семипрайм = 911*1151).

2022-03-02 18:19 UTC, Alowator commented on Task_2_1_1/src/main/java/ru/nsu/alowator/impl/NotPrimeFinder.java
> +    public boolean run() {
Действительно, подходит

2022-03-02 18:34 UTC, Alowator commented on Task_2_1_1/src/main/java/ru/nsu/alowator/App.java
> +    private static void fillArrayWithPrimePositiveNumbers(Integer[] array) {
Ну да, так проще понять, что функция делает. Но в действительности нагрузка при данной реализации почти максимальная, тк если предположить, что простые числа +- равномерно распределены по числовой прямой, то среднее значение чисел в массиве при данной реализации - примерно MAX_INT / 2, что всего в 2 раза меньше наибольшего простого числа, влезающего в int

2022-03-02 18:54 UTC, Alowator commented on Task_2_1_1/src/main/java/ru/nsu/alowator/App.java
> +    private static void fillArrayWithPrimePositiveNumbers(Integer[] array) {
А нет, мое предположение о равномерном распределении простых чисел ошибочное, в действительности ближе к нулю их сильно больше, поэтому действительно лучше забить массив большими числами

2022-03-02 19:03 UTC, Alowator commented on Task_2_1_1/src/main/java/ru/nsu/alowator/App.java
> +    private static void fillArrayWithPrimePositiveNumbers(Integer[] array) {
Однако нужны именно большие числа. Интересное совпадение, что 1048571 это и есть примерно среднее значение в том массиве, что получался в этой раелизации.

2022-03-02 22:13 UTC, Alowator commented
Обновил [типо_readme](https://github.com/Alowator/OOP/pull/6#issue-1143789679)

2022-03-03 06:54 UTC, Leidenn2509 approved these changes

2022-03-03 06:54 UTC, merged