Task_2_2_1
Alowator/OOP pull request #7
Opened 2022-03-14 06:57 UTC by Alowator

Самое важное в этом реквесте на мягкий дедлайн - UML диаграмма классов (`ClassDiagram.png`).

### Архитектура такова:

1.  Пользователям "библиотеки" предоставляется интерфейс `Pizzeria`, туда можно добавлять заказы
2. Сама реализация пиццерии - `RealPizzeria`, она содержит пекарей и склад, который содержит курьеров (как в диаграме)

Пекари и курьеры опрашивают своих masters на предмет наличия заказов/доставок.

### Чего не хватает:
1. unit-тесты
2. javadoc
3. Улучшить реализация опроса пиццерии/склада, тк сейчас пекари долбятся в spinlock
4. Реализация склада и курьеров

2022-03-22 09:21 UTC, Leidenn2509 requested changes
Архитектура выглядит отлично. Осталось только остальные требования реализовать

2022-03-27 22:38 UTC, Alowator commented
### Итак, что мы имеем:
Из задачи по параллельному программированию данная задача превратилась в задачу по тому, **как сделать сериализацию пекарей и курьеров в JSON, не сломав при этом буквы S и D в SOLID**, и данная задача была выполнена. Я гарантирую, что не сломал ни одну букву:
* S - так как каждый класс занимается только своей работой (отражение на сериализацию в JSON увидим позднее)
* O - так как экземпляр каждого класса всегда один
* L - так как наследование отсутствует
* I - так как интерфейсы отсутствуют (кроме `storage`, но там буква не сломана)
* D - так как сериализация объектов абстрагирована от логики программы

### Чтобы достичь этого, применяем [многоуровневую архитектуру](https://ru.wikipedia.org/wiki/Многоуровневая_архитектура)
* Самый высокий уровень - `App.java`
* Уровень бизнес логики - `pizzeria`
* Уровень доступа к данным - `storage` (не путать со складом из бизнес логики, склад - `warehouse`)

# `App.java`
Запускает пиццерию, достает сотрудников из `storage` и передает их пиццерии, добавляет заказы.

# `pizzeria`
Тут все примерно понятно, как в `ClassDiagram.png`, есть пиццерия, у нее есть пекари, также у пиццерии есть склад, у которого есть курьеры. Они работают как ожидается, и ничего не знают о том, как и где они хранятся.

В спинлок нигде не долбятся, а как ожидается, ждут `notify()` чтобы приступить к работе.

# `storage`
Хранение сотрудников абстрагировано, это самый нижний уровень приложения. Юнит-тесты `storage` отсутствуют по понятным причинам.
* `Storage.java` - синглтон предоставляющий доступ к необходимым разделам данных (`bakers(), coriers()`)
* `entities` - модели представления данный (собственно абстракция, которой и пользуется приложение)
* `collections` - интерфейсы (абстракция) для доступа к данным
* `impl/json` - собственно реализация интерфейсов, храним персистентные данные на файловой системе в виде json.

#### Что нам дает этот `storage`:
Доступ к данным абстрагирован за интерфейсом. Если завтра я захочу хранить данные пекарей не в JSON на ФС (что очевидно очень плохое решение), а в базе данных, то мне достаточно реализовать класс `SqlBakersCollection`, который реализаует интерфейс `BakersCollection`, и в `Storage.java` вместо `JsonBakersCollection` вернуть `SqlBakersCollection`, при этом в самом приложении не поменяется ничего.

### Было:
`public static BakersCollection bakers() {
        return new JsonBakersCollection();
    }`
### Станет:
`public static BakersCollection bakers() {
        return new SqlBakersCollection();
    }`

2022-03-28 12:08 UTC, Leidenn2509 requested changes
- Курьеры никак не используют свой багажник
- На будущее: запускать потоки и отпускать на них ссылку выглядит неправильно. Вдруг вам понадобиться остановить их, а ссылки на них нет?

2022-03-30 17:04 UTC, Alowator commented
> * Курьеры никак не используют свой багажник

Теперь используют. НО. Справедливости ради, контракт был выполнен, так как в задании сказано:
> "курьер после очередного заказа обращается на склад и берет одну или
несколько пицц в доставку, но не больше объема своего багажника. Если
склад пуст ожидает появления готовых пицц;"

Мои курьеры раньше брали одну пиццу, все правильно, в задании не сказано, что они должны брать максимальное кол-во пицц))))

> * На будущее: запускать потоки и отпускать на них ссылку выглядит неправильно. Вдруг вам понадобиться остановить их, а ссылки на них нет?
Исправил. Даже помню, как удалял эти ссылки за ненадобностью, но сохранять их действительно стоит.

2022-04-02 12:50 UTC, Leidenn2509 approved these changes

2022-04-03 14:13 UTC, merged