Task_2_3_1
Alowator/OOP pull request #8
Opened 2022-04-11 16:58 UTC by Alowator

### Идея:
Попробую реализовать взаимодействие игры и интерфейса через **callback'и**
То есть, по нажатию на кнопку начинается игра - создается объект `Game`, который получает наш контроллер в виде интерфейса, тогда:
* Контроллер реагирует на нажатия кнопок, и дергает необходимые методы (сама игра остается независима от реализации GUI)
* Игра сама сообщает котроллеру, что и когда необходимо отрисовать (логика игры инкапсулирована в саму игру, а не в GUI, что логично)

### Игра:
* `Game` - содержит `Grid` и `Snake`, управляет ими по команде свыше ☝
* `Grid` - содержит `Cell[][]`
* `Cell`- содержит еду, стены, змейку
* `Snake` - содержит `List[Cell]`, основная ее задача - управлять логикой перемещения

2022-04-19 09:16 UTC, Leidenn2509 requested changes
Не забудьте разделить модель и FX по пакетам

2022-04-19 09:16 UTC, Leidenn2509 commented on Task_2_3_1/src/main/java/ru/nsu/alowator/core/Cell.java
> +    private final int raw;
row

2022-06-15 21:34 UTC, Alowator commented
### Итак, что мы имеем:
Предыдущая идея сделать ядро независимым (на callback'ах) оказалась не очень удачной, 
так как надо разруливать многопоточность.

Теперь схема MVC реализована в полном виде, именно Controller дергает все обновления модели.
Делает контроллер это все из потока UI с помощью `Timeline`. Никаких проблем нет, так как у нас 
один обычный (даже не асинхронный) поток.

# `Application.java`
Точка входа.

# `contoller`
Тут живет JavaFX контроллер, главный - `Main.java`, тут обрабатываем все UI последствия...
Окно настроек открывается отсюда же. За настройки ответственность несет отдельны контроллер `Settings.java`

# `core`
Модель нашей игры. Куча классов примитивной логики. Остановимся на самых важных аспектах:
* `View` - интерфейс, который вью собственно и должен реализовывать
* в `core/frame` лежит `record`, который мы отдаем нашему `View` для отрисовки, это состояние игры.

## `core/entities/Enemies.java`
Главный герой данной лабы. 
Тут лежит вся логика поведения вражеских змеек, и сами эти же змейки.

Змейки ищут пути до еды используя алгоритм поиска максимального потока в графе
(Алгоритм Форда-Фалкерсона в самом простом виде). 

Что мы делаем - берем сток (абстрактная ячейка поля), разрешаем 
движение от нее до каждой из головы змеек, далее берем исток, его мы соединяем со всеми клетками еды,
движение по полю в графе строится как ожидается - из каждой клетки можно попасть во все соседние,
за исключением стен, вражеских змеек и головы змейки игрока.

Как итог имеем нереально жесткий интеллект змеек, каждый шаг они перестраивают этот граф, 
ищут в нем максимальный поток, и поворачивают соответственно найденому потоку.

Эти змеек можно победить, как минимум потому что в данной реализации змейка игрока имеет преимущество -
она поворачивает первая. Также змейки не умеют смотреть на несколько шагов вперед, поэтому могут залезать в тупик.
Однако они опасаются (воспринимают как стены) другие змейки, соответственно играют сообща и не откусывают куски
друг друга.

2022-06-15 21:35 UTC, Alowator commented
Тесты по понятным причинам есть только для модели игры.

2022-06-15 21:43 UTC, Alowator commented
![Screenshot 2022-06-16 044230](https://user-images.githubusercontent.com/66881554/173934983-b713ef5b-e9a9-42a1-aa14-4a3183c7fc72.png)
Визуализация примитивного случая, как работает алгоритм.

2022-06-16 08:18 UTC, Leidenn2509 approved these changes

2022-06-16 08:19 UTC, merged